export default {
  announcement_header: 'LOCATION',
  announcement_content: 'Bow Valley Ranche - 15979 Bow Bottom Trail SE, Calgary, AB',
  not_implemented_heading: 'Sorry - This section has not yet been implemented',
  not_implemented_details: 'Check back in a couple weeks for updates!',
  copyright: '2022 Reilly Steere',
  gallery_intro: 'We are in the gallery now, dudes',
  header_invite: 'We Cordially Invite You To The Wedding of Laura-Anne and Reilly',
  information_itinerary: 'Information & Itinerary',
  invite_details: 'Save The Date: August 19, 2023',
  itinerary: "This site will be updated more frequently as we get closer to the date of the wedding - check the FAQ for suggestions on things to do in (and around) Calgary while you're here and our recommendations for where to stay and how to get to the venue",
  post_address: '#308 725 4 ST NE, Calgary AB T2E 3S7',
  rsvp_heading: 'RSVP',
  rsvp_details: "Please check your invite for a QR Code that will allow you to let us know you're coming and what email will be best to contact you at - future updates will also use this to allow you to specify any dietary concerns you might have and select your meal",
  tarnell_and_autumn: "Reilly & Laura-Anne's",
  wedding: 'Wedding',
};
