export default {
  announcement_header: 'Guess what!',
  announcement_content: 'We are going to get married and now you have to come to our wedding',
  contact: '(587) 234-4811 \n richardtarnell@gmail.com',
  copyright: '2021 JavaScriptJunkies',
  gallery_intro: 'We are in the gallery now, dudes',
  header_invite: 'We Cordially Invite You To The Wedding of Autumn and Tarnell',
  information_itinerary: 'Information & Itinerary',
  invite_details: 'Save The Date: August 19, 2023',
  itinerary: 'Where am I going? What Time do I need to be there? Check the FAQ!',
  post_address: '1234 Fake Ave Edmonton, Alberta T9X 1R4',
  rsvp_heading: 'RSVP',
  rsvp_details: "To RSVP do this thing that I haven't programmed yet",
  tarnell_and_autumn: "Tarnell & Autumn's",
  wedding: 'Wedding',
};
